# Generated by Django 3.1.1 on 2020-10-27 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodType', models.IntegerField(blank=True, null=True)),
                ('resultType', models.IntegerField(blank=True, null=True)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood1', models.FloatField()),
                ('mood2', models.FloatField()),
                ('mood3', models.FloatField()),
                ('mood4', models.FloatField()),
                ('mood5', models.FloatField()),
                ('mood6', models.FloatField()),
                ('mood7', models.FloatField()),
                ('mood8', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('userNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
