# Generated by Django 3.1.1 on 2020-10-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0002_remove_emotion_mood8'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodType', models.IntegerField(blank=True, null=True)),
                ('question', models.CharField(max_length=150)),
            ],
        ),
    ]
