# Generated by Django 3.1.1 on 2020-10-30 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emotion', '0003_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='option',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='userNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
