# Generated by Django 3.1.1 on 2020-11-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0004_auto_20201030_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quetionNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
