# Generated by Django 3.1.1 on 2020-11-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0005_question_quetionno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quetionNo',
            new_name='questionNo',
        ),
    ]
